version: 2.1
parameters:
    run_basedeployment:
        default: true
        type: boolean
    run_performancetesting:
        default: false
        type: boolean
    run_smoketesting:
        default: false
        type: boolean    


python_env: &python_env
  docker:
    - image: circleci/python:2.7-stretch-browsers

install_awscli: &install_awscli
  name: "Install awscli"
  command: |
    sudo pip install awscli --upgrade
install_deploysuite: &install_deploysuite
  name: Installation of install_deploysuite.
  command: |
    git clone --branch v1.4.1 https://github.com/topcoder-platform/tc-deploy-scripts ../buildscript
    cp ./../buildscript/master_deploy.sh .
    cp ./../buildscript/buildenv.sh .
    cp ./../buildscript/awsconfiguration.sh .

# Instructions of deployment
deploy_steps: &deploy_steps
  - checkout
  - attach_workspace:
      at: ./workspace
  - run: *install_awscli
  - run: *install_deploysuite
  - setup_remote_docker
  - run: docker build -t ${APPNAME}:latest .
  - deploy:
      name: "Running Masterscript -  deploy tc-project-service "
      command: |
        ./awsconfiguration.sh $DEPLOY_ENV
        source awsenvconf
        ./buildenv.sh -e $DEPLOY_ENV -b ${LOGICAL_ENV}-${APPNAME}-deployvar
        source buildenvvar
        ./master_deploy.sh -d ECS -e $DEPLOY_ENV -t latest -s ${LOGICAL_ENV}-global-appvar,${LOGICAL_ENV}-${APPNAME}-appvar -i ${APPNAME}

         echo "======= Running Masterscript - deploy projects-api-consumers ==========="
        if [ -e ${LOGICAL_ENV}-${APPNAME}-appvar.json ]; then  sudo rm -vf ${LOGICAL_ENV}-${APPNAME}-appvar.json; fi
        ./buildenv.sh -e $DEPLOY_ENV -b ${LOGICAL_ENV}-${APPNAME}-consumers-deployvar
        source buildenvvar
        ./master_deploy.sh -d ECS -e $DEPLOY_ENV -t latest -s ${LOGICAL_ENV}-global-appvar,${LOGICAL_ENV}-${APPNAME}-appvar -i ${APPNAME}
        #testing code changes
        if [[ true ]]; then
        ./buildenv.sh -e $DEPLOY_ENV -b ${LOGICAL_ENV}-qa-v1-appvar
        source buildenvvar 
        curl --request POST \
        --url https://circleci.com/api/v2/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pipeline \
        --header "Circle-Token: ${QA_USER_TOKEN}" \
        --header 'content-type: application/json' \
        --data '{"branch":"'"$CIRCLE_BRANCH"'","parameters":{"run_smoketesting":true , "run_basedeployment": false}}'
        fi 


jobs:
  UnitTests:
    docker:
      - image: circleci/node:12.16.1
      - image: circleci/postgres:9.6.2-alpine
        environment:
        - POSTGRES_USER: circle_test
        - POSTGRES_DB: circle_test
      - image: elasticsearch:2.3
    environment:
      DEPLOY_ENV: "DEV"
      LOGICAL_ENV: "dev"
      APPNAME: "projects-api"
    steps:
      - checkout
      - run:
          name: "Install dependeency"
          command: |
              sudo apt update
              sudo apt install curl
              sudo apt install python-pip
      - run: *install_awscli
      - run: *install_deploysuite
      - setup_remote_docker
      - restore_cache:
          key: test-node-modules-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: test-node-modules-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run lint
      - run:
          name: "Running Masterscript -  deploy tc-project-service "
          command: |
            ./awsconfiguration.sh $DEPLOY_ENV
            source awsenvconf
            ./buildenv.sh -e $DEPLOY_ENV -b ${LOGICAL_ENV}-${APPNAME}-testvar
            source buildenvvar
            npm run test
            rm -f buildenvvar
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  deployProd:
    <<: *python_env
    environment:
      DEPLOY_ENV: "PROD"
      LOGICAL_ENV: "prod"
      APPNAME: "projects-api"
    steps: *deploy_steps

  deployDev:
    <<: *python_env
    environment:
      DEPLOY_ENV: "DEV"
      LOGICAL_ENV: "dev"
      APPNAME: "projects-api"
    steps: *deploy_steps

  Connect-Automation-Testing: 
    working_directory: ~/connect-smoke-testing/connect-app-e2e-test 
    docker: 
      - image: circleci/node:11-browsers 
    steps: 
      - checkout 
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: 
          name: browser Update
          command: './node_modules/.bin/webdriver-manager update'      
      - run: 
          name: browser start
          command: './node_modules/.bin/webdriver-manager start'   
          background: true    
      - run: # run tests
          name: Execute Smoke Test
          command: npm test
  
workflows:
  version: 2
  Connect Project Services:
    when: << pipeline.parameters.run_basedeployment >>
    jobs:
      - UnitTests:
          context : org-global
      - deployDev:
          context : org-global
          requires:
            - UnitTests
          filters:
            branches:
              only: ['develop', 'connect-performance-testing']
      - deployProd:
          context : org-global
          requires:
            - UnitTests
          filters:
            branches:
              only: ['master']   

  Smoke  Testing:
    when: << pipeline.parameters.run_smoketesting >>
    jobs:
      - Connect-Automation-Testing:
          filters:
            branches:
              only: ['connect-smoke-testing']